{% set version = "0.10.1" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}

package:
  name: symengine
  version: {{ version }}

source:
  url: https://github.com/symengine/symengine/releases/download/v{{ version }}/symengine-{{ version }}.tar.gz
  sha256: 9c007c99e9633f5549a55fa7a66ebcbcf9e04092eb55f7bb781c22b9cf0570c4

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - make             # [unix]
    - ninja            # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gmp              # [unix]
    - mpir             # [win]
    - mpfr
    - mpc
    - llvmdev <14
    - zlib
    - libflint
  run:
    - gmp              # [unix]
    - mpir             # [win]
    - mpfr
    - mpc
    - libflint

test:
  commands:
    - if not exist %LIBRARY_INC%\\symengine\\basic.h exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\symengine.lib exit 1          # [win]
    - if not exist %LIBRARY_BIN%\\symengine-{{ maj_min }}.dll exit 1          # [win]
    - test -f $PREFIX/include/symengine/basic.h                 # [unix]
    - test -f $PREFIX/lib/libsymengine.so                       # [linux]
    - test -f $PREFIX/lib/libsymengine.dylib                    # [osx]

about:
  home: https://github.com/symengine/symengine
  license: MIT
  license_file: LICENSE
  summary: SymEngine is a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
