{% set version = "0.2.0" %}
{% set commit = "v0.2.0" %}

package:
  name: symengine
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/symengine/symengine/archive/{{ commit }}.tar.gz
  sha256: 64d050b0b9decd12bf4ea3b7d18d3904dd7cb8baaae9fbac1b8068e3c59709be

build:
  number: 1
  skip: true        # [win and not py35]
  features:
    - vc14          # [win and py35]

requirements:
  build:
    - toolchain 2.0.0    # [unix]
    - cmake
    - gmp           # [unix]
    - mpfr          # [unix]
    - mpc           # [unix]
    - mpir          # [win]
    - python        # [win]
  run:
    - gmp           # [unix]
    - mpfr          # [unix]
    - mpc           # [unix]
    - mpir          # [win]

test:
  requires:
    - python 3.5.*  # [win and py35]
  commands:
    - if not exist %LIBRARY_INC%\\symengine\\basic.h exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\symengine.lib exit 1          # [win]
    - if not exist %LIBRARY_BIN%\\symengine.dll exit 1          # [win]
    - test -f $PREFIX/include/symengine/basic.h                 # [unix]
    - test -f $PREFIX/lib/libsymengine.so                       # [linux]
    - test -f $PREFIX/lib/libsymengine.dylib                    # [osx]

about:
  home: https://github.com/symengine/symengine
  license: MIT
  license_file: LICENSE
  summary: 'SymEngine is a fast symbolic manipulation library, written in C++'

extra:
  recipe-maintainers:
    - isuruf
    - certik
