# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NFdgzHHjbc+cItr/KKqqDVYmuIxRZ5SPSAsu3x5ozhf84pd9vRSl1qY6eYXo1KmQjfybMH3l+6IaDiWcWo5j8BDTg2rzZCmmPTOcn1aKdMmHuKJ9j2Mp0HuHvL3/HuEAPDUFXVfQHpZmLjdNzugNbtLzriMxGx1gkXWwP5m8wmrG1GGQxz85dh28qNVoL1Ge4s9i1+hHubam8qSOsGetfprxE4Zpp/3lc5phtbv8MJ9ep2J+g9+GBzx00vRpSWc7Yk9gEHjT9n3+wxVtZ3Kh1L/vV1+2T6Ez3I6TQoPWXX2JrvUsecCAr87iDCwPBKQjpoqLFwc/qDV6BeMGT5FgXZ+3jUc2Psj9bhq1BT8efVuXsDksbfiG1/60++s80g898mGtT5veTd5OJWMzN2YTOpoAvWyN6hVe03fBKf0cY8PTA1L9xNINLFbA3WDZaG41N47H1H/bWcwgE1w/tiAzkGYojZTCAdBIcs6g0pk+jp1J+/sv0aZRaWV2QBpp74WIATpVvip9JvJCySS0QDJxSyRxAwnYl/+IvGfIfZ+OzVy+AMVKC3LBjJr261Wmpe1aUv1Spcch6MZtqb00C8o5oDdP+VDvJBvoU1Wwfrfn1yriqAV+7s//P7Blvr8wyhgLQc2nFlaBuS7hqrFUeb++o9N4xvE6/MOn0dPDKRALl6E="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
